#!/usr/bin/env python3
"""Exact certificate for the transported-anchor transition groupoid at n=7.

For each reduced two-spectator support, enumerate every history obtained by

  1. deleting either spectator to reach the exact n=6 atlas,
  2. choosing any available direct seed chart,
  3. choosing a full-rank parent edge block, and
  4. carrying the deleted spectator when it is exterior to that edge.

For the five generic words this gives 17 histories but only 12 distinct
144-dimensional quotient coordinates.  The coordinates are generated by
three pair-local copies of the n=6 wall operator theta:

    A = (theta^{-1})_(H_R,V_a),
    B = (theta^{-1})_(H_R,V_b),
    S = -(theta)_(H_L,V_b).

The exceptional word 212 has three histories and two core coordinates.  Its
two full 148-dimensional coordinates are related by S direct-sum id_H: the
intrinsic kappa_212 residual is fixed and no residual-to-core shear occurs.

Every matching, completion, and transition is reconstructed independently
over F_1009 and F_1013.  Centered lifts agree and all defining identities are
then checked over the integers.  NumPy is used only for integer and
finite-field arithmetic; no floating-point computation occurs.
"""

from itertools import combinations
from pathlib import Path
from tempfile import TemporaryDirectory

import numpy as np

from all_n_pairwise_terminal_descent_certificate import right_encoder
from n6_response_4simplex_modular_certificate import (
    rank_mod,
    right_inverse_data_mod,
)
from n6_spectator_chart_transition_certificate import (
    reconstruct_charts,
    theta_operator,
)
from n7_exceptional_core_decomposition_certificate import (
    action_generators,
    integer_array,
    tensor_kappa,
)
from n7_internal_word_atlas_certificate import (
    CORE_DIMENSION,
    EDGE_DIMENSION,
    GAPS,
    OLD_EDGE_DIMENSION,
    PRIMES,
    SUPPORTS,
    carry_leftmost,
    carry_rightmost,
    casimir_numerators,
    centered_scaled_lift,
    exact_rank,
    local_matching,
    parent_data,
    prepare_restrictions,
    sigma_plus_encoder,
)
from second_response_simplex_differential_certificate import (
    left_nullspace_mod,
)


EXCEPTIONAL_WORD = (2, 1, 2)
EXCEPTIONAL_SUPPORT = (1, 3, 4, 6)
QUOTIENT_DIMENSIONS = {
    **{word: CORE_DIMENSION for word in SUPPORTS},
    EXCEPTIONAL_WORD: CORE_DIMENSION + 4,
}
ALL_SUPPORTS = {**SUPPORTS, EXCEPTIONAL_WORD: EXCEPTIONAL_SUPPORT}

# A history is
#   (new spectator, old spectator, parent position, parent chart,
#    actual anchored edge, exterior side).
EXPECTED_GROUPS = {
    (1, 1, 3): (
        (
            (5, 4, 4, (3, 4), (1, 6), "right"),
            (5, 4, 4, (3, 4), (3, 6), "right"),
        ),
    ),
    (1, 2, 2): (
        ((3, 5, 4, (3, 4), (1, 2), "left"),),
        ((5, 3, 3, (1, 2), (4, 6), "right"),),
        ((5, 3, 3, (3, 4), (4, 6), "right"),),
    ),
    (1, 3, 1): (
        ((3, 4, 3, (1, 2), (1, 2), "left"),),
        ((3, 4, 3, (3, 4), (1, 2), "left"),),
        ((4, 3, 3, (1, 2), (5, 6), "right"),),
        ((4, 3, 3, (3, 4), (5, 6), "right"),),
    ),
    (2, 2, 1): (
        ((2, 4, 3, (1, 2), (1, 3), "left"),),
        ((2, 4, 3, (3, 4), (1, 3), "left"),),
        (
            (4, 2, 2, (1, 2), (5, 6), "right"),
            (4, 2, 2, (1, 4), (5, 6), "right"),
        ),
    ),
    (3, 1, 1): (
        (
            (2, 3, 2, (1, 2), (1, 4), "left"),
            (2, 3, 2, (1, 2), (1, 6), "left"),
            (2, 3, 2, (1, 4), (1, 4), "left"),
            (2, 3, 2, (1, 4), (1, 6), "left"),
        ),
    ),
    EXCEPTIONAL_WORD: (
        ((2, 5, 4, (3, 4), (1, 6), "left"),),
        (
            (5, 2, 2, (1, 2), (1, 6), "right"),
            (5, 2, 2, (1, 4), (1, 6), "right"),
        ),
    ),
}

MINIMAL_POLYNOMIALS = {
    "A": (1, -1, -1, 1),
    "B": (1, -1, -1, 1),
    "S": (-1, -1, 1, 1),
    "SB": (-1, 0, 1, -1, 0, 1),
    "AS": (1, 1, -2, -2, 1, 1),
    "ASB": (1, 0, -1, 1, -1, -1, 1, -1, 0, 1),
}


def prepare_prime(prime):
    restrictions, encoder = prepare_restrictions(prime)
    plus_encoder = sigma_plus_encoder() % prime
    plus_pivots, plus_inverse = right_inverse_data_mod(
        plus_encoder, prime
    )
    if not np.array_equal(
        plus_pivots, np.arange(EDGE_DIMENSION)
    ):
        raise AssertionError("left suspension pivot order changed")
    desuspension = plus_inverse @ encoder % prime
    return restrictions, desuspension


def enumerate_support(
    word,
    support,
    quotient_dimension,
    restrictions,
    desuspension,
    charts,
    prime,
):
    matching = local_matching(support, restrictions, prime)
    quotient = left_nullspace_mod(matching, prime)
    if quotient.shape[0] != quotient_dimension:
        raise AssertionError("unexpected local quotient dimension")

    actual_edges = tuple(combinations(support, 2))
    block_data = {}
    for edge_index in range(6):
        columns = slice(
            edge_index * EDGE_DIMENSION,
            (edge_index + 1) * EDGE_DIMENSION,
        )
        block = quotient[:, columns] % prime
        if rank_mod(block, prime) == quotient_dimension:
            block_data[edge_index] = (
                block,
                right_inverse_data_mod(block, prime),
            )

    candidates = []
    spectators = tuple(gap for gap in GAPS if gap not in support)
    for new_spectator in spectators:
        old_spectator, parent_position = parent_data(
            support, new_spectator
        )
        for chart_key, chart in charts[parent_position].items():
            for edge_index, edge in enumerate(actual_edges):
                if edge_index not in block_data:
                    continue
                remaining = tuple(
                    gap for gap in GAPS if gap not in edge
                )
                if new_spectator == remaining[0]:
                    side = "left"
                elif new_spectator == remaining[-1]:
                    side = "right"
                else:
                    continue

                old_block = chart[
                    :,
                    edge_index * OLD_EDGE_DIMENSION:
                    (edge_index + 1) * OLD_EDGE_DIMENSION,
                ]
                if rank_mod(old_block % prime, prime) != 48:
                    continue
                if side == "left":
                    anchor = carry_leftmost(
                        old_block,
                        edge,
                        old_spectator,
                        new_spectator,
                    ) % prime
                else:
                    anchor = carry_rightmost(
                        old_block,
                        desuspension,
                        prime,
                    )
                if rank_mod(anchor, prime) != CORE_DIMENSION:
                    raise AssertionError("transported anchor lost rank")

                block, (pivots, inverse) = block_data[edge_index]
                normalizer = anchor[:, pivots] @ inverse % prime
                if np.count_nonzero(
                    (normalizer @ block - anchor) % prime
                ):
                    continue
                core = normalizer @ quotient % prime
                history = (
                    new_spectator,
                    old_spectator,
                    parent_position,
                    chart_key,
                    edge,
                    side,
                )
                candidates.append((history, core))

    groups = []
    for history, core in candidates:
        for group in groups:
            if np.array_equal(group["core"], core):
                group["histories"].append(history)
                break
        else:
            groups.append({
                "core": core,
                "histories": [history],
            })

    return {
        "word": word,
        "matching": matching,
        "matching_rank": rank_mod(matching, prime),
        "groups": groups,
    }


def process_prime(prime, charts, temporary_directory):
    print(f"building transported-anchor census mod {prime}", flush=True)
    restrictions, desuspension = prepare_prime(prime)
    result = {}
    for word, support in ALL_SUPPORTS.items():
        print("  word", "".join(map(str, word)), flush=True)
        item = enumerate_support(
            word,
            support,
            QUOTIENT_DIMENSIONS[word],
            restrictions,
            desuspension,
            charts,
            prime,
        )
        matching16 = centered_scaled_lift(
            item.pop("matching"), 16, prime
        )
        path = (
            Path(temporary_directory)
            / f"transition_matching_{''.join(map(str, word))}_{prime}.npy"
        )
        np.save(path, matching16)
        item["matching_path"] = path
        result[word] = item
    return result


def centered_lift(matrix, prime):
    result = matrix.copy()
    result[result > prime // 2] -= prime
    return result.astype(np.int64)


def pair_operator(local, quaternion_slot, vector_slot):
    """Embed an H tensor V operator in H_L,H_R,V_a,V_b coordinates."""

    result = np.zeros((CORE_DIMENSION, CORE_DIMENSION), dtype=np.int64)
    for first_h in range(4):
        for second_h in range(4):
            for first_vector in range(3):
                for second_vector in range(3):
                    values = [
                        first_h,
                        second_h,
                        first_vector,
                        second_vector,
                    ]
                    h = values[quaternion_slot]
                    vector = values[2 + vector_slot]
                    local_source = 3 * h + vector
                    source = (
                        36 * first_h
                        + 9 * second_h
                        + 3 * first_vector
                        + second_vector
                    )
                    for local_target in np.flatnonzero(
                        local[:, local_source]
                    ):
                        new_h, new_vector = divmod(
                            int(local_target), 3
                        )
                        target_values = values.copy()
                        target_values[quaternion_slot] = new_h
                        target_values[2 + vector_slot] = new_vector
                        target = (
                            36 * target_values[0]
                            + 9 * target_values[1]
                            + 3 * target_values[2]
                            + target_values[3]
                        )
                        result[target, source] = local[
                            local_target, local_source
                        ]
    return result


def minimal_polynomial_mod(matrix, prime, maximum_degree=16):
    identity = np.eye(matrix.shape[0], dtype=np.int64)
    powers = [identity]
    power = identity
    for _degree in range(1, maximum_degree + 1):
        power = power @ matrix % prime
        rows = np.stack(
            [item.reshape(-1) for item in powers]
        ) % prime
        pivots, inverse = right_inverse_data_mod(rows, prime)
        target = (-power.reshape(-1)) % prime
        coefficients = target[pivots] @ inverse % prime
        if not np.count_nonzero(
            (coefficients @ rows - target) % prime
        ):
            result = [int(value) for value in coefficients] + [1]
            return tuple(
                value - prime if value > prime // 2 else value
                for value in result
            )
        powers.append(power.copy())
    raise AssertionError("minimal polynomial degree bound was too small")


def evaluate_polynomial_exact(matrix, coefficients):
    identity = np.eye(matrix.shape[0], dtype=np.int64)
    row_norm = int(np.max(np.sum(np.abs(matrix), axis=1)))
    bound = 0
    for coefficient in reversed(coefficients):
        bound = bound * row_norm + abs(coefficient)
    if bound >= 2**62:
        raise AssertionError("int64 polynomial bound is insufficient")

    result = np.zeros_like(matrix)
    for coefficient in reversed(coefficients):
        result = result @ matrix + coefficient * identity
    return result


def report():
    checks = []

    def check(name, condition):
        checks.append((name, bool(condition)))

    print("reconstructing exact n=6 parent charts", flush=True)
    _, charts = reconstruct_charts()

    with TemporaryDirectory() as temporary_directory:
        modular = {
            prime: process_prime(
                prime, charts, temporary_directory
            )
            for prime in PRIMES
        }

        integer_groups = {}
        matching16 = {}
        for word in ALL_SUPPORTS:
            first = modular[PRIMES[0]][word]
            second = modular[PRIMES[1]][word]
            first_matching = np.load(first["matching_path"])
            second_matching = np.load(second["matching_path"])
            matching16[word] = first_matching

            check(
                f"word {word}: both primes lift the same 16*matching",
                np.array_equal(first_matching, second_matching),
            )
            check(
                f"word {word}: matching alphabet is 0,+/-1,+/-2",
                set(int(value) for value in first_matching.reshape(-1))
                <= {-2, -1, 0, 1, 2},
            )
            expected_rank = (
                1796 if word == EXCEPTIONAL_WORD else 1800
            )
            for prime in PRIMES:
                check(
                    f"word {word}: matching rank mod {prime}",
                    modular[prime][word]["matching_rank"]
                    == expected_rank,
                )

            first_groups = first["groups"]
            second_groups = second["groups"]
            check(
                f"word {word}: completion count is prime-independent",
                len(first_groups) == len(second_groups),
            )
            histories = tuple(
                tuple(group["histories"]) for group in first_groups
            )
            check(
                f"word {word}: exhaustive history census",
                histories == EXPECTED_GROUPS[word],
            )

            lifts = []
            for index, (first_group, second_group) in enumerate(
                zip(first_groups, second_groups)
            ):
                check(
                    f"word {word}, core {index}: history labels agree",
                    first_group["histories"]
                    == second_group["histories"],
                )
                first_lift = centered_lift(
                    first_group["core"], PRIMES[0]
                )
                second_lift = centered_lift(
                    second_group["core"], PRIMES[1]
                )
                check(
                    f"word {word}, core {index}: integer lift agrees",
                    np.array_equal(first_lift, second_lift),
                )
                check(
                    f"word {word}, core {index}: exact cancellation",
                    not np.count_nonzero(
                        first_lift @ first_matching
                    ),
                )
                for prime in PRIMES:
                    check(
                        f"word {word}, core {index}: rank 144 mod {prime}",
                        rank_mod(
                            modular[prime][word]["groups"][index]["core"],
                            prime,
                        ) == CORE_DIMENSION,
                    )
                lifts.append(first_lift)
            integer_groups[word] = lifts

        crt_bound = EDGE_DIMENSION * (4 * 3**5) * 2 + 16
        crt_modulus = PRIMES[0] * PRIMES[1]
        check(
            "the matching CRT bound fits below the modulus",
            crt_bound < crt_modulus,
        )

    theta = theta_operator()
    identity_theta = np.eye(12, dtype=np.int64)
    theta_inverse = -theta @ theta + theta + identity_theta
    check(
        "the closed theta inverse is exact",
        np.array_equal(
            theta @ theta_inverse,
            identity_theta,
        ) and np.array_equal(
            theta_inverse @ theta,
            identity_theta,
        ),
    )

    # Factor order: H_L, H_R, V_a, V_b.
    A = pair_operator(theta_inverse, 1, 0)
    B = pair_operator(theta_inverse, 1, 1)
    S = pair_operator(-theta, 0, 1)
    identity_core = np.eye(CORE_DIMENSION, dtype=np.int64)
    A_inverse = pair_operator(theta, 1, 0)
    B_inverse = pair_operator(theta, 1, 1)
    S_inverse = pair_operator(-theta_inverse, 0, 1)
    check(
        "A, B, and S are integral automorphisms",
        all(
            np.array_equal(forward @ inverse, identity_core)
            and np.array_equal(inverse @ forward, identity_core)
            for forward, inverse in (
                (A, A_inverse),
                (B, B_inverse),
                (S, S_inverse),
            )
        ),
    )

    core122 = integer_groups[(1, 2, 2)]
    core131 = integer_groups[(1, 3, 1)]
    core221 = integer_groups[(2, 2, 1)]
    check("word 122 has chain S,A",
          np.array_equal(core122[1], S @ core122[0])
          and np.array_equal(core122[2], A @ core122[1]))
    check("word 131 has chain B,S,A",
          np.array_equal(core131[1], B @ core131[0])
          and np.array_equal(core131[2], S @ core131[1])
          and np.array_equal(core131[3], A @ core131[2]))
    check("word 221 has chain B,S",
          np.array_equal(core221[1], B @ core221[0])
          and np.array_equal(core221[2], S @ core221[1]))
    check(
        "the two exterior words each have one coordinate",
        len(integer_groups[(1, 1, 3)]) == 1
        and len(integer_groups[(3, 1, 1)]) == 1,
    )

    exceptional = integer_groups[EXCEPTIONAL_WORD]
    kappa = tensor_kappa(integer_array(right_encoder(4)))
    check(
        "kappa kills the exceptional matching over Z",
        not np.count_nonzero(
            kappa @ matching16[EXCEPTIONAL_WORD]
        ),
    )
    check(
        "the exceptional cores are related by S with no kappa shear",
        np.array_equal(exceptional[1], S @ exceptional[0]),
    )
    full_first = np.concatenate((exceptional[0], kappa), axis=0)
    full_second = np.concatenate((exceptional[1], kappa), axis=0)
    full_transition = np.zeros((148, 148), dtype=np.int64)
    full_transition[:144, :144] = S
    full_transition[144:, 144:] = np.eye(4, dtype=np.int64)
    check(
        "the full exceptional transition is S direct-sum id_H",
        np.array_equal(full_second, full_transition @ full_first),
    )
    for prime in PRIMES:
        check(
            f"both exceptional full coordinates have rank 148 mod {prime}",
            rank_mod(full_first % prime, prime) == 148
            and rank_mod(full_second % prime, prime) == 148,
        )

    _, target_generators, _ = action_generators()
    check(
        "A, B, and S are SO(3)-equivariant over Z",
        all(
            not np.count_nonzero(generator @ operator
                                 - operator @ generator)
            for generator in target_generators
            for operator in (A, B, S)
        ),
    )
    check("A and S commute on disjoint factor pairs",
          np.array_equal(A @ S, S @ A))
    check("A and B do not commute",
          exact_rank(A @ B - B @ A) == 64)
    check("S and B do not commute",
          exact_rank(S @ B - B @ S) == 51)

    operators = {
        "A": A,
        "B": B,
        "S": S,
        "SB": S @ B,
        "AS": A @ S,
        "ASB": A @ S @ B,
    }
    for name, operator in operators.items():
        polynomial = MINIMAL_POLYNOMIALS[name]
        check(
            f"{name}: exact annihilating polynomial",
            not np.count_nonzero(
                evaluate_polynomial_exact(operator, polynomial)
            ),
        )
        for prime in PRIMES:
            check(
                f"{name}: minimal polynomial mod {prime}",
                minimal_polynomial_mod(operator % prime, prime)
                == polynomial,
            )

    projector_numerators, _ = casimir_numerators()
    top_projector = projector_numerators[4]
    check(
        "A and B negate the top-spin sector while S fixes it",
        not np.count_nonzero(top_projector @ (A + identity_core))
        and not np.count_nonzero(top_projector @ (B + identity_core))
        and not np.count_nonzero(top_projector @ (S - identity_core)),
    )
    check(
        "the full ASB passage fixes the top-spin sector",
        not np.count_nonzero(
            top_projector @ (operators["ASB"] - identity_core)
        ),
    )

    print("history counts / distinct coordinates:")
    for word in ALL_SUPPORTS:
        groups = EXPECTED_GROUPS[word]
        print(
            " ",
            "".join(map(str, word)),
            sum(len(group) for group in groups),
            "/",
            len(groups),
        )
    print("generic transition chains: 122=S,A; 131=B,S,A; 221=B,S")
    print("commutator ranks [A,B], [S,B]:", 64, 51)
    print("minimal polynomials:")
    for name, polynomial in MINIMAL_POLYNOMIALS.items():
        print(" ", name, polynomial)
    print("exceptional transition: S direct-sum id_H; kappa shear rank 0")
    print("CRT bound/modulus:", crt_bound, crt_modulus)

    for name, passed in checks:
        print(f"[{'PASS' if passed else 'FAIL'}] {name}")
    failed = [name for name, passed in checks if not passed]
    if failed:
        raise SystemExit("FAILED: " + ", ".join(failed))
    print("ALL CHECKS PASSED")


if __name__ == "__main__":
    report()
